### ISSUE TITLE
after searching location, pop-window for location doesn't look right

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/maps4all#36]
<img width="1117" alt="screen shot 2016-10-04 at 9 59 34 pm" src="https://cloud.githubusercontent.com/assets/4250521/19098752/ebbcd938-8a7d-11e6-8ae0-5afe8e00ee9c.png">
<img width="1115" alt="screen shot 2016-10-04 at 9 59 23 pm" src="https://cloud.githubusercontent.com/assets/4250521/19098753/ebbd4972-8a7d-11e6-85d3-2252250b6b4d.png">

**Comment by anniemeng** [comment]
fixed in refactor #75
