### ISSUE TITLE
"Map View" vs. "List View" looks off, "More Information" looks off in "Map View", doesn't show up in "List View", which also has blank space on bottom of list

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/maps4all#37]
<img width="1280" alt="screen shot 2016-10-04 at 10 12 04 pm" src="https://cloud.githubusercontent.com/assets/4250521/19098978/e2500904-8a7f-11e6-9dda-708ed9d1834e.png">
<img width="1280" alt="screen shot 2016-10-04 at 10 11 56 pm" src="https://cloud.githubusercontent.com/assets/4250521/19098979/e25051f2-8a7f-11e6-85fb-b246afab071f.png">
<img width="1280" alt="screen shot 2016-10-04 at 10 11 46 pm" src="https://cloud.githubusercontent.com/assets/4250521/19098981/e251a840-8a7f-11e6-9ed5-e19a73c4f337.png">
<img width="1280" alt="screen shot 2016-10-04 at 10 11 24 pm" src="https://cloud.githubusercontent.com/assets/4250521/19098980/e250bf5c-8a7f-11e6-8710-3a13ffab27f7.png">

**Comment by anniemeng** [comment]
completely refactored
