### ISSUE TITLE
Editing a single resource option descriptor fails

### ISSUE THREAD

**Issue by kyle-rosenbluth** [hack4impact/maps4all#95]
This is most likely related to something I made in #69, but I can't seem to figure out what it is. Try editing a resource with an option descriptor, maybe change the option descriptor to have an additional option. Then save.

**Comment by yoninachmany** [comment]
maybe call db.commit in a try catch and see if u get an integrityerror or something else - i think the model may need to be changed, but im not sure about the best way

**Comment by anniemeng** [comment]
fixed in #111
